on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Linter
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.21.0 && go get -u golang.org/x/lint/golint &&  [ -z `go env GOPATH`/bin/golint ./... | grep ".go" ] && true || false && [ -z `gofmt -l . | grep ".go"` ] && true || false
    - name: Security
      run: go get github.com/securego/gosec/cmd/gosec; `go env GOPATH`/bin/gosec ./...
    - name: Tests
      run: go test -v ./...
